### ISSUE TITLE
All mods on client required on the server to pass the check?

### ISSUE THREAD

**Issue by NielsPilgaard** [starmun-0010/actually-compatible#1]
Hai \o

In Enigmatica 6, the server check fails despite client being compatible with the server. Several client-only mods are present, a few server-only mods are present on the server.

Is this to be expected? :)

**Comment by starmun-0010** [comment]
Hello Hello o/

From the client side logs of E6, with ```Actually Compatible``` installed on both client and server:
![image](https://user-images.githubusercontent.com/5557278/143807504-26dd2d98-d07f-4c15-bfdf-d2d4f2851853.png)

If JEED is supposed to be client side only then they need to implement proper sidedness.
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

Tested with JEED installed on both sides of E6, and the server shows up as compatible.
![image](https://user-images.githubusercontent.com/5557278/143808189-cf9400ef-cf95-44b9-86cc-7c19f3888a56.png)

**Comment by NielsPilgaard** [comment]
Ahh I see, thank you, I've readded JEED to the server files, works like a charm now! I really appreciate your help :D
