### ISSUE TITLE
[1.18-Forge] Crash when attempting to boot game.

### ISSUE THREAD

**Issue by Gbergz** [starmun-0010/actually-compatible#2]
Title^

**MC**: 1.18
**Forge**: 38.0.12
**Mod**: 0.1.1

Logs:
https://gist.github.com/Gbergz/069f9bf7c39061cfd10470480c9f9439

**-** Gbergz

**Comment by starmun-0010** [comment]
Woops, pushed  wrong mixin reference.
Fixed in 0.1.1a.
