### ISSUE TITLE
crashes on the newest forge

### ISSUE THREAD

**Issue by ZEROX7** [starmun-0010/actually-compatible#3]
forge 39.0.59 client
[crash-2022-01-25_22.34.56-server.txt](https://github.com/starmun-0010/actually-compatible/files/7937355/crash-2022-01-25_22.34.56-server.txt)

**Comment by starmun-0010** [comment]
@ZEROX7 Please let me know if 0.1.2 version fixes the issue.

**Comment by starmun-0010** [comment]
Should be fixed in version 0.1.2,
please test and let me know.
